package com.example.ui.localization

import androidx.compose.runtime.Composable
import androidx.compose.runtime.CompositionLocalProvider
import androidx.compose.runtime.staticCompositionLocalOf
import androidx.compose.ui.platform.LocalLayoutDirection
import androidx.compose.ui.unit.LayoutDirection

/**
 * Supported UI languages in SALAH
 */
enum class AppLanguage(
    val code: String,
    val nativeName: String,
    val englishName: String,
    val isRtl: Boolean = false,
    val description: String
) {
    ENGLISH(
        code = "en",
        nativeName = "English",
        englishName = "English",
        isRtl = false,
        description = "Default international interface"
    ),
    ARABIC(
        code = "ar",
        nativeName = "العربية",
        englishName = "Arabic",
        isRtl = true,
        description = "واجهة عربية كاملة مع الأرقام والمصطلحات الشرعية"
    ),
    FRENCH(
        code = "fr",
        nativeName = "Français",
        englishName = "French",
        isRtl = false,
        description = "Interface complète en langue française"
    ),
    INDONESIAN(
        code = "id",
        nativeName = "Bahasa Indonesia",
        englishName = "Indonesian",
        isRtl = false,
        description = "Antarmuka lengkap Bahasa Indonesia (Waktu Sholat & Al-Qur'an)"
    ),
    TURKISH(
        code = "tr",
        nativeName = "Türkçe",
        englishName = "Turkish",
        isRtl = false,
        description = "Eksiksiz Türkçe arayüz (Namaz Vakitleri & Kur'an)"
    ),
    URDU(
        code = "ur",
        nativeName = "اردو",
        englishName = "Urdu",
        isRtl = true,
        description = "مکمل اردو انٹرفیس مع اوقاتِ نماز اور قرآنی اصطلاحات"
    ),
    MALAY(
        code = "ms",
        nativeName = "Bahasa Melayu",
        englishName = "Malay",
        isRtl = false,
        description = "Antara muka lengkap Bahasa Melayu (Waktu Solat & Al-Quran)"
    ),
    BENGALI(
        code = "bn",
        nativeName = "বাংলা",
        englishName = "Bengali",
        isRtl = false,
        description = "সম্পূর্ণ বাংলা ইন্টারফেস (নামাজের সময়সূচী ও কুরআন)"
    ),
    RUSSIAN(
        code = "ru",
        nativeName = "Русский",
        englishName = "Russian",
        isRtl = false,
        description = "Полный интерфейс на русском языке (Время намаза и Коран)"
    ),
    GERMAN(
        code = "de",
        nativeName = "Deutsch",
        englishName = "German",
        isRtl = false,
        description = "Vollständige deutsche Benutzeroberfläche (Gebetszeiten & Koran)"
    ),
    SPANISH(
        code = "es",
        nativeName = "Español",
        englishName = "Spanish",
        isRtl = false,
        description = "Interfaz completa en español (Horarios de oración y Corán)"
    );

    companion object {
        fun fromNameOrCode(nameOrCode: String): AppLanguage {
            return values().firstOrNull {
                it.nativeName.equals(nameOrCode, ignoreCase = true) ||
                it.englishName.equals(nameOrCode, ignoreCase = true) ||
                it.code.equals(nameOrCode, ignoreCase = true) ||
                it.name.equals(nameOrCode, ignoreCase = true)
            } ?: ENGLISH
        }
    }
}

/**
 * Full UI String Dictionary Interface
 */
data class UiStrings(
    val appName: String,
    // Bottom navigation
    val navToday: String,
    val navPrayer: String,
    val navQuran: String,
    val navQibla: String,
    val navSettings: String,

    // Home / Today Screen
    val nextPrayerLabel: String,
    val adhanAt: String,
    val viewDetails: String,
    val currentPeriod: String,
    val skyPeriodSuffix: String,
    val hoursUnit: String,
    val minsUnit: String,
    val secsUnit: String,
    val todaysPrayers: String,
    val tapToMarkCompleted: String,
    val continueReading: String,
    val continueButton: String,
    val sourceLabel: String,
    val alertsActive: String,
    val silentModeOn: String,
    val masjidMode: String,
    val resetToRealtime: String,
    val onlineStatus: String,
    val offlineStatus: String,
    val syncingStatus: String,

    // Prayer names
    val fajr: String,
    val sunrise: String,
    val dhuhr: String,
    val asr: String,
    val maghrib: String,
    val isha: String,

    // Prayer Screen
    val transparentCalculationSource: String,
    val todaysTimes: String,
    val prayerTimesHeader: String,
    val vigilsAndNightPeriods: String,
    val imsakTitle: String,
    val midnightTitle: String,
    val lastThirdTitle: String,
    val monthlyCalendarHeader: String,
    val todayBtn: String,

    // Qibla Screen
    val qiblaDirectionTitle: String,
    val sensoryCompassSubtitle: String,
    val magneticInterferenceDetected: String,
    val moveAwayMetal: String,
    val kaabaDistance: String,
    val trueNorth: String,
    val magneticNorth: String,
    val calibratedStatus: String,
    val facingQibla: String,
    val turnTowardsKaaba: String,

    // Quran Screen
    val surahTab: String,
    val pageTab: String,
    val juzTab: String,
    val hizbTab: String,
    val bookmarksTab: String,
    val searchSurahPlaceholder: String,
    val continueReadingBar: String,
    val versesCount: String,
    val meccan: String,
    val medinan: String,

    // Settings Screen
    val settingsTitle: String,
    val sectionGeneral: String,
    val languageLabel: String,
    val appThemeLabel: String,
    val timeFormatLabel: String,
    val sectionPrayerCalc: String,
    val locationLabel: String,
    val methodLabel: String,
    val madhhabLabel: String,
    val adjustmentsLabel: String,
    val hijriCalibrationLabel: String,
    val sectionAudioAlerts: String,
    val adhanCallLabel: String,
    val perPrayerModesLabel: String,
    val prePrayerReminderLabel: String,
    val adhanSoundLabel: String,
    val adhanVolumeLabel: String,
    val vibrationOnlyLabel: String,
    val sectionQuran: String,
    val riwayahLabel: String,
    val scriptStyleLabel: String,
    val reciterLabel: String,
    val translationLabel: String,
    val arabicTextSizeLabel: String,
    val sectionMasjidMode: String,
    val globalSilentLabel: String,
    val autoMasjidModeLabel: String,
    val autoMasjidDurationLabel: String,
    val sectionSystemDiagnostics: String,
    val compassDiagnosticsLabel: String,
    val networkSyncLabel: String,
    val resetDefaultsLabel: String,
    val privacyPhilosophyTitle: String,

    // Dialog & Common Buttons
    val cancel: String,
    val confirm: String,
    val save: String,
    val done: String,
    val close: String,

    /**
     * Copy added by the redesign.
     *
     * These are not fields on [UiStrings] on purpose. A Kotlin data class
     * generates a `copy` and a `componentN` per property, and the JVM caps a
     * method signature at 255 slots - so folding 160-odd strings into the same
     * class compiles cleanly and then dies at runtime with
     * `ClassFormatError: Too many arguments in method signature`. A second
     * data class keeps both well inside the limit.
     *
     * Read them as `strings.more.someLabel`. Every value here replaces an
     * English literal that used to sit directly in a layout file, which is
     * exactly why none of them could ever be translated. They are English
     * defaults; add a per-language override as each is translated.
     */
    val more: UiStringsMore = UiStringsMore()
)

/** Copy the redesign added, kept in its own class to stay under the JVM method limit. */
data class UiStringsMore(
    val actionCancel: String = "Cancel",
    val actionSave: String = "Save",
    val actionClose: String = "Close",
    val actionBack: String = "Back",
    val actionReset: String = "Reset",
    val search: String = "Search",
    val clearSearch: String = "Clear search",
    val loading: String = "Loading",
    val somethingWentWrong: String = "Something went wrong",
    val tryAgain: String = "Try again",
    val todayTitle: String = "Today",
    val changeLocation: String = "Change location",
    val prayerMarkedDone: String = "Prayer marked as prayed",
    val prayerMarkedPending: String = "Prayer marked as not prayed",
    val silenceAdhan: String = "Silence",
    val adhanPlayingLabel: String = "Adhan playing",
    val sunAltitude: String = "Sun",
    val observatoryTitle: String = "Sky",
    val observatorySubtitle: String = "Astronomy for %s",
    val solarAltitude: String = "Sun altitude",
    val solarAzimuth: String = "Sun azimuth",
    val aboveHorizon: String = "Above horizon",
    val belowHorizon: String = "Below horizon",
    val trueNorthSuffix: String = "true north",
    val lunarPhase: String = "Moon phase",
    val illumination: String = "Illumination",
    val waxing: String = "Waxing",
    val waning: String = "Waning",
    val skyPeriodLabel: String = "Sky period",
    val timeScrubber: String = "Time of day",
    val previewingTime: String = "Previewing %s",
    val realTime: String = "Real time",
    val calculationSource: String = "%s · %s",
    val prayerTimesTitle: String = "Prayer times",
    val methodology: String = "Method",
    val madhhabLabelShort: String = "Asr method",
    val appliedAdjustments: String = "Manual adjustments",
    val computedOnDevice: String = "Computed on this device",
    val lastVerified: String = "Last checked",
    val previousDay: String = "Previous day",
    val nextDay: String = "Next day",
    val selectDate: String = "Select date",
    val minutesShort: String = "min",
    val daysShort: String = "days",
    val noAdjustment: String = "No adjustment",
    val quranTitle: String = "Quran",
    val corpusSummary: String = "114 surahs · 30 juz · 6,236 verses",
    val surahsTab: String = "Surahs",
    val noBookmarksTitle: String = "No saved verses",
    val noBookmarksMessage: String = "Tap the bookmark icon while reading to save a verse here.",
    val noSearchResults: String = "No matches",
    val searchSurahsAndVerses: String = "Search surahs and verses",
    val searchPages: String = "Search page number",
    val versesFound: String = "%d verses",
    val surahsFound: String = "%d surahs",
    val verseCount: String = "%d verses",
    val verseReference: String = "%d:%d",
    val selectSurah: String = "Select surah",
    val textSize: String = "Text size",
    val readingLayout: String = "Layout",
    val cardsLayout: String = "Per verse",
    val continuousLayout: String = "Continuous",
    val showTranslation: String = "Show translation",
    val hideTranslation: String = "Hide translation",
    val translationCredit: String = "Saheeh International",
    val readingSaved: String = "Reading position saved",
    val recitingLabel: String = "Reciting",
    val stopAudio: String = "Stop",
    val playVerse: String = "Play",
    val pauseVerse: String = "Pause",
    val bookmarkVerse: String = "Save verse",
    val removeBookmark: String = "Remove saved verse",
    val copyVerse: String = "Copy",
    val shareVerse: String = "Share",
    val verseCopied: String = "Verse copied",
    val selectVerseHint: String = "Select a verse to read it here.",
    val hizbHalfFirst: String = "1st half",
    val hizbHalfSecond: String = "2nd half",
    val juzOf: String = "Juz %d",
    val hizbOf: String = "Hizb %d",
    val hizbInJuz: String = "Juz %d, %s",
    val qiblaTitle: String = "Qibla",
    val qiblaSubtitle: String = "Direction to the Kaaba",
    val useCurrentLocation: String = "Use my location",
    val calibrateCompass: String = "Calibrate compass",
    val calibrationTitle: String = "Calibrate the compass",
    val calibrationMessage: String = "Move the device in a figure-eight pattern a few times to let the sensor settle.",
    val solarReferenceTitle: String = "Check with the sun",
    val sunAzimuth: String = "Sun direction",
    val sunAltitudeValue: String = "Sun height",
    val qiblaBearing: String = "Qibla direction",
    val sunBelowHorizon: String = "The sun is below the horizon, so it cannot be used as a reference right now.",
    val sunAligned: String = "The sun is almost in the Qibla direction. Face it to confirm.",
    val sunToTheLeft: String = "The Qibla is about %d° to the left of the sun.",
    val sunToTheRight: String = "The Qibla is about %d° to the right of the sun.",
    val sunOpposite: String = "The Qibla is in the opposite direction to the sun.",
    val magneticInterference: String = "Magnetic interference",
    val magneticInterferenceMessage: String = "Reading may be inaccurate. Move away from metal and electronics.",
    val sectionAppearance: String = "Appearance",
    val sectionLocationAndCalculation: String = "Location & calculation",
    val sectionAlerts: String = "Alerts",
    val sectionAbout: String = "About & diagnostics",
    val livingSkyLabel: String = "Animated sky",
    val livingSkyDescription: String = "Animate the background sky on the Today screen. Uses more battery.",
    val timeFormat24hLabel: String = "24-hour time",
    val chooseLanguage: String = "Language",
    val chooseTheme: String = "Theme",
    val themeSystem: String = "Match system",
    val themeDark: String = "Dark",
    val themeLight: String = "Light",
    val chooseLocation: String = "Location",
    val useGps: String = "Use GPS",
    val customLocation: String = "Enter manually",
    val searchCities: String = "Search cities",
    val chooseMethod: String = "Calculation method",
    val chooseMadhhab: String = "Asr calculation",
    val chooseAdjustments: String = "Minute adjustments",
    val resetAdjustments: String = "Reset all adjustments",
    val chooseHijriOffset: String = "Hijri date offset",
    val chooseAdhanSound: String = "Adhan sound",
    val chooseReciter: String = "Reciter",
    val chooseRiwayah: String = "Riwayah",
    val chooseScript: String = "Script",
    val chooseTranslation: String = "Translation",
    val choosePrePrayerOffset: String = "Reminder before prayer",
    val prePrayerDisabled: String = "Off",
    val perPrayerModes: String = "Alert per prayer",
    val adhanVolume: String = "Volume",
    val testSound: String = "Test sound",
    val stopSound: String = "Stop sound",
    val silentModeLabel: String = "Silence all alerts",
    val autoSilenceLabel: String = "Auto-silence during prayer",
    val autoSilenceDurationLabel: String = "Auto-silence duration",
    val vibrateOnlyLabel: String = "Vibrate only",
    val adhanAtPrayerLabel: String = "Adhan at prayer time",
    val ephemerisCacheLabel: String = "Prayer schedule cache",
    val recomputeSchedule: String = "Recompute 365-day schedule",
    val copyTodaySchedule: String = "Copy today's times",
    val scheduleCopied: String = "Times copied",
    val storageLabel: String = "Storage",
    val clearAudioCache: String = "Clear audio cache",
    val audioCacheCleared: String = "Audio cache cleared",
    val sensorAccuracy: String = "Sensor accuracy",
    val ambientField: String = "Ambient field",
    val checkForUpdates: String = "Check now",
    val resetAllLabel: String = "Reset all settings",
    val resetAllConfirmTitle: String = "Reset all settings?",
    val resetAllConfirmMessage: String = "Calculation, alert and display settings return to their defaults. Your saved verses and prayer log are kept.",
    val settingsReset: String = "Settings reset",
    val nameField: String = "Place name",
    val latitudeField: String = "Latitude",
    val longitudeField: String = "Longitude",
    val invalidCoordinates: String = "Enter a latitude between -90 and 90, and a longitude between -180 and 180.",
    val nameRequired: String = "Enter a name for this place.",
    val locationSaved: String = "Location saved",
    val hizbWord: String = "Hizb",
    val previousSurahLabel: String = "Previous surah",
    val nextSurahLabel: String = "Next surah",
    val isFacingQibla: String = "You are facing the Qibla",
    val rightOfQibla: String = "to the right",
    val leftOfQibla: String = "to the left",
    val juzWord: String = "Juz’",
    val pageWord: String = "Page",
    val privacyNote: String = "Prayer times, the Qibla direction and the Quran are all calculated on this device. Nothing is uploaded.",
)

val EnglishStrings = UiStrings(
    appName = "SALAH",
    navToday = "Today",
    navPrayer = "Prayer",
    navQuran = "Quran",
    navQibla = "Qibla",
    navSettings = "Settings",

    nextPrayerLabel = "NEXT PRAYER",
    adhanAt = "Adhan at",
    viewDetails = "View details",
    currentPeriod = "Current period",
    skyPeriodSuffix = "Sky ✦",
    hoursUnit = "HOURS",
    minsUnit = "MINS",
    secsUnit = "SECS",
    todaysPrayers = "Today's Prayers",
    tapToMarkCompleted = "Tap to mark completed",
    continueReading = "CONTINUE READING",
    continueButton = "Continue",
    sourceLabel = "Source",
    alertsActive = "Alerts Active",
    silentModeOn = "Silent Mode ON",
    masjidMode = "Masjid Mode",
    resetToRealtime = "Reset to Real-Time Sky",
    onlineStatus = "ONLINE",
    offlineStatus = "OFFLINE",
    syncingStatus = "SYNCING",

    fajr = "Fajr",
    sunrise = "Sunrise",
    dhuhr = "Dhuhr",
    asr = "Asr",
    maghrib = "Maghrib",
    isha = "Isha",

    transparentCalculationSource = "Transparent Calculation Source",
    todaysTimes = "TODAY'S TIMES",
    prayerTimesHeader = "PRAYER TIMES",
    vigilsAndNightPeriods = "VIGILS & NIGHT PERIODS",
    imsakTitle = "Imsak (10 min before Fajr)",
    midnightTitle = "Islamic Midnight",
    lastThirdTitle = "Last Third of the Night (Tahajjud)",
    monthlyCalendarHeader = "MONTHLY CALENDAR",
    todayBtn = "Today",

    qiblaDirectionTitle = "Qibla Direction",
    sensoryCompassSubtitle = "Sensory compass pointing to the Kaaba",
    magneticInterferenceDetected = "Magnetic Interference Detected",
    moveAwayMetal = "Move away from metallic objects or tap for calibration.",
    kaabaDistance = "Distance to Kaaba",
    trueNorth = "True North",
    magneticNorth = "Magnetic North",
    calibratedStatus = "HIGH ACCURACY",
    facingQibla = "Facing the Kaaba",
    turnTowardsKaaba = "Turn towards the Kaaba",

    surahTab = "Surah",
    pageTab = "Page",
    juzTab = "Juz'",
    hizbTab = "Hizb",
    bookmarksTab = "Bookmarks",
    searchSurahPlaceholder = "Search Surah by name or number...",
    continueReadingBar = "Continue Reading",
    versesCount = "verses",
    meccan = "Meccan",
    medinan = "Medinan",

    settingsTitle = "Settings & Configuration",
    sectionGeneral = "GENERAL & LOCALIZATION",
    languageLabel = "Language",
    appThemeLabel = "App Theme",
    timeFormatLabel = "24-Hour Time Format",
    sectionPrayerCalc = "PRAYER TIMES & CALCULATION",
    locationLabel = "Location",
    methodLabel = "Calculation Method",
    madhhabLabel = "Asr Juristic Madhhab",
    adjustmentsLabel = "Manual Minute Adjustments",
    hijriCalibrationLabel = "Hijri Date Calibration",
    sectionAudioAlerts = "AUDIO ADHAN & NOTIFICATIONS",
    adhanCallLabel = "Adhan Call at Prayer Time",
    perPrayerModesLabel = "Per-Prayer Alert Modes",
    prePrayerReminderLabel = "Pre-Prayer Reminder Timing",
    adhanSoundLabel = "Adhan Recitation Voice",
    adhanVolumeLabel = "Adhan Volume & Audio Tester",
    vibrationOnlyLabel = "Vibration Only (Silent)",
    sectionQuran = "THE NOBLE QURAN & RECITATION",
    riwayahLabel = "Riwāyāt (Recitation Tradition)",
    scriptStyleLabel = "Quran Script Style",
    reciterLabel = "Audio Reciter",
    translationLabel = "Translation & Exegesis",
    arabicTextSizeLabel = "Quran Arabic Text Size",
    sectionMasjidMode = "MASJID MODE & DISTURBANCE PROTECTION",
    globalSilentLabel = "Global Silent Mode",
    autoMasjidModeLabel = "Auto Masjid Silence Mode",
    autoMasjidDurationLabel = "Silence Duration During Prayer",
    sectionSystemDiagnostics = "SYSTEM & DIAGNOSTICS",
    compassDiagnosticsLabel = "Compass Sensors & Diagnostics",
    networkSyncLabel = "Network Synchronization & Source",
    resetDefaultsLabel = "Reset Preferences to Factory Defaults",
    privacyPhilosophyTitle = "Privacy & Philosophy",

    cancel = "Cancel",
    confirm = "Confirm",
    save = "Save",
    done = "Done",
    close = "Close"
)

val ArabicStrings = UiStrings(
    appName = "صلاة",
    navToday = "اليوم",
    navPrayer = "الصلاة",
    navQuran = "القرآن",
    navQibla = "القبلة",
    navSettings = "الإعدادات",

    nextPrayerLabel = "الصلاة القادمة",
    adhanAt = "الأذان في",
    viewDetails = "عرض التفاصيل",
    currentPeriod = "الوقت الحالي",
    skyPeriodSuffix = "سماء ✦",
    hoursUnit = "ساعة",
    minsUnit = "دقيقة",
    secsUnit = "ثانية",
    todaysPrayers = "صلوات اليوم",
    tapToMarkCompleted = "اضغط للتعليم عند الأداء",
    continueReading = "متابعة التلاوة",
    continueButton = "متابعة",
    sourceLabel = "المصدر",
    alertsActive = "التنبيهات مفعّلة",
    silentModeOn = "الوضع الصامت مفعّل",
    masjidMode = "وضع المسجد",
    resetToRealtime = "العودة للوقت الفعلي",
    onlineStatus = "متصل",
    offlineStatus = "بدون اتصال",
    syncingStatus = "مزامنة",

    fajr = "الفجر",
    sunrise = "الشروق",
    dhuhr = "الظهر",
    asr = "العصر",
    maghrib = "المغرب",
    isha = "العشاء",

    transparentCalculationSource = "مصدر الحساب الشرعي الشفاف",
    todaysTimes = "أوقات اليوم",
    prayerTimesHeader = "مواقيت الصلاة",
    vigilsAndNightPeriods = "قيام الليل وأوقات السحر",
    imsakTitle = "الإمساك (١٠ دقائق قبل الفجر)",
    midnightTitle = "منتصف الليل الشرعي",
    lastThirdTitle = "الثلث الأخير من الليل (التهجد)",
    monthlyCalendarHeader = "التقويم الشهري",
    todayBtn = "اليوم",

    qiblaDirectionTitle = "اتجاه القبلة",
    sensoryCompassSubtitle = "بوصلة مستشعرات دقيقة نحو الكعبة المشرفة",
    magneticInterferenceDetected = "تم رصد تشويش مغناطيسي",
    moveAwayMetal = "ابتعد عن الأجسام المعدنية أو اضغط للمعايرة.",
    kaabaDistance = "المسافة إلى الكعبة",
    trueNorth = "الشمال الحقيقي",
    magneticNorth = "الشمال المغناطيسي",
    calibratedStatus = "دقة عالية",
    facingQibla = "أنت باتجاه القبلة تماماً",
    turnTowardsKaaba = "استدر نحو الكعبة المشرفة",

    surahTab = "السورة",
    pageTab = "الصفحة",
    juzTab = "الجزء",
    hizbTab = "الحزب",
    bookmarksTab = "الإشارات",
    searchSurahPlaceholder = "ابحث عن السورة بالاسم أو الرقم...",
    continueReadingBar = "متابعة القراءة",
    versesCount = "آيات",
    meccan = "مكية",
    medinan = "مدنية",

    settingsTitle = "الإعدادات والخيارات",
    sectionGeneral = "عام واللغة",
    languageLabel = "اللغة",
    appThemeLabel = "مظهر التطبيق",
    timeFormatLabel = "صيغة ٢٤ ساعة",
    sectionPrayerCalc = "مواقيت الصلاة والحساب",
    locationLabel = "الموقع الجغرافي",
    methodLabel = "طريقة الحساب",
    madhhabLabel = "المذهب الفقهي (العصر)",
    adjustmentsLabel = "تعديل الدقائق يدوياً",
    hijriCalibrationLabel = "معايرة التاريخ الهجري",
    sectionAudioAlerts = "صوت الأذان والإشعارات",
    adhanCallLabel = "نداء الأذان عند دخول الوقت",
    perPrayerModesLabel = "أوضاع التنبيه لكل صلاة",
    prePrayerReminderLabel = "تذكير قبل الصلاة",
    adhanSoundLabel = "صوت المؤذن",
    adhanVolumeLabel = "مستوى الصوت وتجربة الأذان",
    vibrationOnlyLabel = "اهتزاز فقط (صامت)",
    sectionQuran = "القرآن الكريم والتلاوة",
    riwayahLabel = "الرواية القرآنية",
    scriptStyleLabel = "رسم المصحف الشريف",
    reciterLabel = "القارئ الصوتي",
    translationLabel = "الترجمة والتفسير",
    arabicTextSizeLabel = "حجم الخط القرآني",
    sectionMasjidMode = "وضع المسجد وحماية الخشوع",
    globalSilentLabel = "الوضع الصامت العام",
    autoMasjidModeLabel = "الوضع الصامت التلقائي للصلاة",
    autoMasjidDurationLabel = "مدة الصمت أثناء الصلاة",
    sectionSystemDiagnostics = "النظام والمستشعرات",
    compassDiagnosticsLabel = "مستشعرات البوصلة والتشخيص",
    networkSyncLabel = "المزامنة والمصدر",
    resetDefaultsLabel = "إعادة ضبط المصنع",
    privacyPhilosophyTitle = "الخصوصية والمنهج",

    cancel = "إلغاء",
    confirm = "تأكيد",
    save = "حفظ",
    done = "تم",
    close = "إغلاق"
)

val FrenchStrings = UiStrings(
    appName = "SALAH",
    navToday = "Aujourd'hui",
    navPrayer = "Prière",
    navQuran = "Coran",
    navQibla = "Qibla",
    navSettings = "Paramètres",

    nextPrayerLabel = "PROCHAINE PRIÈRE",
    adhanAt = "Adhan à",
    viewDetails = "Voir détails",
    currentPeriod = "Période actuelle",
    skyPeriodSuffix = "Ciel ✦",
    hoursUnit = "HEURES",
    minsUnit = "MIN",
    secsUnit = "SEC",
    todaysPrayers = "Prières d'aujourd'hui",
    tapToMarkCompleted = "Appuyez pour marquer accomplie",
    continueReading = "CONTINUER LA LECTURE",
    continueButton = "Continuer",
    sourceLabel = "Source",
    alertsActive = "Alertes actives",
    silentModeOn = "Mode silencieux ACTIF",
    masjidMode = "Mode Mosquée",
    resetToRealtime = "Retour au temps réel",
    onlineStatus = "EN LIGNE",
    offlineStatus = "HORS LIGNE",
    syncingStatus = "SYNCHRO",

    fajr = "Fajr",
    sunrise = "Lever du soleil",
    dhuhr = "Dhuhr",
    asr = "Asr",
    maghrib = "Maghrib",
    isha = "Isha",

    transparentCalculationSource = "Source de calcul transparente",
    todaysTimes = "HORAIRES DU JOUR",
    prayerTimesHeader = "HORAIRES DE PRIÈRE",
    vigilsAndNightPeriods = "VEILLES & PÉRIODES DE NUIT",
    imsakTitle = "Imsak (10 min avant Fajr)",
    midnightTitle = "Minuit islamique",
    lastThirdTitle = "Dernier tiers de la nuit (Tahajjud)",
    monthlyCalendarHeader = "CALENDRIER MENSUEL",
    todayBtn = "Aujourd'hui",

    qiblaDirectionTitle = "Direction de la Qibla",
    sensoryCompassSubtitle = "Boussole sensorielle orientée vers la Kaaba",
    magneticInterferenceDetected = "Interférence magnétique détectée",
    moveAwayMetal = "Éloignez-vous des métaux ou calibrez.",
    kaabaDistance = "Distance à la Kaaba",
    trueNorth = "Nord géographique",
    magneticNorth = "Nord magnétique",
    calibratedStatus = "HAUTE PRÉCISION",
    facingQibla = "Face à la Kaaba",
    turnTowardsKaaba = "Tournez-vous vers la Kaaba",

    surahTab = "Sourate",
    pageTab = "Page",
    juzTab = "Juz'",
    hizbTab = "Hizb",
    bookmarksTab = "Signets",
    searchSurahPlaceholder = "Rechercher par nom ou numéro...",
    continueReadingBar = "Reprendre la lecture",
    versesCount = "versets",
    meccan = "Mecquoise",
    medinan = "Médinoise",

    settingsTitle = "Paramètres & Configuration",
    sectionGeneral = "GÉNÉRAL & LOCALISATION",
    languageLabel = "Langue",
    appThemeLabel = "Thème de l'application",
    timeFormatLabel = "Format horaire 24h",
    sectionPrayerCalc = "HORAIRES & CALCULS",
    locationLabel = "Emplacement",
    methodLabel = "Méthode de calcul",
    madhhabLabel = "École juridique (Asr)",
    adjustmentsLabel = "Ajustements manuels (minutes)",
    hijriCalibrationLabel = "Calibrage calendrier hégirien",
    sectionAudioAlerts = "AUDIO ADHAN & NOTIFICATIONS",
    adhanCallLabel = "Appel à la prière à l'heure",
    perPrayerModesLabel = "Modes d'alerte par prière",
    prePrayerReminderLabel = "Rappel avant la prière",
    adhanSoundLabel = "Voix de l'Adhan",
    adhanVolumeLabel = "Volume et test audio de l'Adhan",
    vibrationOnlyLabel = "Vibreur seul (Silencieux)",
    sectionQuran = "LE SAINT CORAN & RÉCITATION",
    riwayahLabel = "Riwāyah (Tradition de récitation)",
    scriptStyleLabel = "Style de calligraphie coranique",
    reciterLabel = "Récitateur audio",
    translationLabel = "Traduction & Exégèse",
    arabicTextSizeLabel = "Taille du texte arabe",
    sectionMasjidMode = "MODE MOSQUÉE & TRANQUILLITÉ",
    globalSilentLabel = "Mode silencieux global",
    autoMasjidModeLabel = "Mode silencieux auto prière",
    autoMasjidDurationLabel = "Durée du silence pendant la prière",
    sectionSystemDiagnostics = "SYSTÈME & CAPTEURS",
    compassDiagnosticsLabel = "Capteurs boussole & diagnostic",
    networkSyncLabel = "Synchronisation réseau & source",
    resetDefaultsLabel = "Rétablir les paramètres par défaut",
    privacyPhilosophyTitle = "Confidentialité & Philosophie",

    cancel = "Annuler",
    confirm = "Confirmer",
    save = "Enregistrer",
    done = "Terminé",
    close = "Fermer"
)

val IndonesianStrings = UiStrings(
    appName = "SALAH",
    navToday = "Hari Ini",
    navPrayer = "Jadwal",
    navQuran = "Al-Qur'an",
    navQibla = "Kiblat",
    navSettings = "Pengaturan",

    nextPrayerLabel = "WAKTU SHOLAT BERIKUTNYA",
    adhanAt = "Adzan pukul",
    viewDetails = "Lihat rincian",
    currentPeriod = "Waktu sekarang",
    skyPeriodSuffix = "Langit ✦",
    hoursUnit = "JAM",
    minsUnit = "MENIT",
    secsUnit = "DETIK",
    todaysPrayers = "Jadwal Sholat Hari Ini",
    tapToMarkCompleted = "Ketuk untuk tandai selesai",
    continueReading = "LANJUTKAN MEMBACA",
    continueButton = "Lanjut",
    sourceLabel = "Sumber",
    alertsActive = "Pengingat Aktif",
    silentModeOn = "Mode Senyap AKTIF",
    masjidMode = "Mode Masjid",
    resetToRealtime = "Kembali ke Waktu Nyata",
    onlineStatus = "ONLINE",
    offlineStatus = "OFFLINE",
    syncingStatus = "SINKRONISASI",

    fajr = "Subuh",
    sunrise = "Terbit",
    dhuhr = "Dzuhur",
    asr = "Ashar",
    maghrib = "Maghrib",
    isha = "Isya",

    transparentCalculationSource = "Sumber Perhitungan Transparan",
    todaysTimes = "JADWAL SHOLAT HARI INI",
    prayerTimesHeader = "JADWAL SHOLAT",
    vigilsAndNightPeriods = "WAKTU MALAM & TAHAJUD",
    imsakTitle = "Imsak (10 mnt sebelum Subuh)",
    midnightTitle = "Tengah Malam Islam",
    lastThirdTitle = "Sepertiga Malam Terakhir (Tahajud)",
    monthlyCalendarHeader = "KALENDER BULANAN",
    todayBtn = "Hari Ini",

    qiblaDirectionTitle = "Arah Kiblat",
    sensoryCompassSubtitle = "Kompas sensor akurat mengarah ke Ka'bah",
    magneticInterferenceDetected = "Gangguan Magnetik Terdeteksi",
    moveAwayMetal = "Jauhkan dari benda logam atau ketuk kalibrasi.",
    kaabaDistance = "Jarak ke Ka'bah",
    trueNorth = "Utara Sejati",
    magneticNorth = "Utara Magnetik",
    calibratedStatus = "AKURASI TINGGI",
    facingQibla = "Tepat Menghadap Ka'bah",
    turnTowardsKaaba = "Arahkan ke Ka'bah",

    surahTab = "Surah",
    pageTab = "Halaman",
    juzTab = "Juz",
    hizbTab = "Hizb",
    bookmarksTab = "Penanda",
    searchSurahPlaceholder = "Cari Surah nama atau nomor...",
    continueReadingBar = "Lanjutkan Bacaan",
    versesCount = "ayat",
    meccan = "Makkiyyah",
    medinan = "Madaniyyah",

    settingsTitle = "Pengaturan & Konfigurasi",
    sectionGeneral = "UMUM & LOKALISASI",
    languageLabel = "Bahasa",
    appThemeLabel = "Tema Aplikasi",
    timeFormatLabel = "Format Waktu 24 Jam",
    sectionPrayerCalc = "JADWAL SHOLAT & PERHITUNGAN",
    locationLabel = "Lokasi",
    methodLabel = "Metode Perhitungan",
    madhhabLabel = "Mazhab Fikih (Ashar)",
    adjustmentsLabel = "Penyesuaian Menit Manual",
    hijriCalibrationLabel = "Kalibrasi Penanggalan Hijriah",
    sectionAudioAlerts = "ADZAN & PEMBERITAHUAN",
    adhanCallLabel = "Kumandangkan Adzan Tepat Waktu",
    perPrayerModesLabel = "Mode Pengingat Per Sholat",
    prePrayerReminderLabel = "Pengingat Sebelum Sholat",
    adhanSoundLabel = "Suara Muadzin Adzan",
    adhanVolumeLabel = "Volume & Uji Suara Adzan",
    vibrationOnlyLabel = "Getar Saja (Senyap)",
    sectionQuran = "AL-QUR'AN & TILAWAH",
    riwayahLabel = "Riwayat Bacaan",
    scriptStyleLabel = "Gaya Rasm Al-Qur'an",
    reciterLabel = "Qari Audio",
    translationLabel = "Terjemahan & Tafsir",
    arabicTextSizeLabel = "Ukuran Huruf Arab",
    sectionMasjidMode = "MODE MASJID & KEKHUSYUKAN",
    globalSilentLabel = "Mode Senyap Global",
    autoMasjidModeLabel = "Senyap Otomatis Saat Sholat",
    autoMasjidDurationLabel = "Durasi Senyap Saat Sholat",
    sectionSystemDiagnostics = "SISTEM & DIAGNOSTIK",
    compassDiagnosticsLabel = "Sensor Kompas & Diagnostik",
    networkSyncLabel = "Sinkronisasi Jaringan & Sumber",
    resetDefaultsLabel = "Kembalikan ke Pengaturan Pabrik",
    privacyPhilosophyTitle = "Privasi & Filosofi",

    cancel = "Batal",
    confirm = "Konfirmasi",
    save = "Simpan",
    done = "Selesai",
    close = "Tutup"
)

val TurkishStrings = UiStrings(
    appName = "SALAH",
    navToday = "Bugün",
    navPrayer = "Vakitler",
    navQuran = "Kur'an",
    navQibla = "Kıble",
    navSettings = "Ayarlar",

    nextPrayerLabel = "SONRAKİ VAKİT",
    adhanAt = "Ezan vakti",
    viewDetails = "Ayrıntıları gör",
    currentPeriod = "Mevcut vakit",
    skyPeriodSuffix = "Gökyüzü ✦",
    hoursUnit = "SAAT",
    minsUnit = "DK",
    secsUnit = "SN",
    todaysPrayers = "Günün Namaz Vakitleri",
    tapToMarkCompleted = "Kılındı işaretlemek için dokunun",
    continueReading = "OKUMAYA DEVAM ET",
    continueButton = "Devam",
    sourceLabel = "Kaynak",
    alertsActive = "Bildirimler Açık",
    silentModeOn = "Sessiz Mod AÇIK",
    masjidMode = "Cami Modu",
    resetToRealtime = "Gerçek Zamana Dön",
    onlineStatus = "ÇEVRİMİÇİ",
    offlineStatus = "ÇEVRİMDIŞI",
    syncingStatus = "EŞİTLENİYOR",

    fajr = "İmsak",
    sunrise = "Güneş",
    dhuhr = "Öğle",
    asr = "İkindi",
    maghrib = "Akşam",
    isha = "Yatsı",

    transparentCalculationSource = "Şeffaf Hesaplama Kaynağı",
    todaysTimes = "BUGÜNÜN VAKİTLERİ",
    prayerTimesHeader = "NAMAZ VAKİTLERİ",
    vigilsAndNightPeriods = "TEHECCÜD & GECE VAKİTLERİ",
    imsakTitle = "İmsak (Fecr-i Sadık)",
    midnightTitle = "Şer'i Gece Yarısı",
    lastThirdTitle = "Gecenin Son Üçte Biri (Teheccüd)",
    monthlyCalendarHeader = "AYLIK İMSAKİYE",
    todayBtn = "Bugün",

    qiblaDirectionTitle = "Kıble Yönü",
    sensoryCompassSubtitle = "Kabe-i Muazzama'yı gösteren hassas pusula",
    magneticInterferenceDetected = "Manyetik Parazit Tespit Edildi",
    moveAwayMetal = "Metal nesnelerden uzaklaşın veya kalibre edin.",
    kaabaDistance = "Kabe'ye Mesafe",
    trueNorth = "Gerçek Kuzey",
    magneticNorth = "Manyetik Kuzey",
    calibratedStatus = "YÜKSEK DOĞRULUK",
    facingQibla = "Kıbleye Yöneldiniz",
    turnTowardsKaaba = "Kabe'ye Doğru Dönün",

    surahTab = "Sure",
    pageTab = "Sayfa",
    juzTab = "Cüz",
    hizbTab = "Hizb",
    bookmarksTab = "Yer İmleri",
    searchSurahPlaceholder = "Sure adı veya numarası ara...",
    continueReadingBar = "Kaldığın Yerden Oku",
    versesCount = "ayet",
    meccan = "Mekki",
    medinan = "Medeni",

    settingsTitle = "Ayarlar & Yapılandırma",
    sectionGeneral = "GENEL & YERELLEŞTİRME",
    languageLabel = "Dil",
    appThemeLabel = "Uygulama Teması",
    timeFormatLabel = "24 Saat Zaman Formatı",
    sectionPrayerCalc = "NAMAZ VAKİTLERİ & HESAPLAMA",
    locationLabel = "Konum",
    methodLabel = "Hesaplama Yöntemi",
    madhhabLabel = "İkindi Mezhebi",
    adjustmentsLabel = "Manuel Dakika Düzeltmeleri",
    hijriCalibrationLabel = "Hicri Takvim Ayarı",
    sectionAudioAlerts = "EZAN SESİ & BİLDİRİMLER",
    adhanCallLabel = "Vaktinde Ezan Oku",
    perPrayerModesLabel = "Vakitlere Özel Uyarı Modları",
    prePrayerReminderLabel = "Vakit Öncesi Hatırlatıcı",
    adhanSoundLabel = "Müezzin Ezan Sesi",
    adhanVolumeLabel = "Ezan Sesi Düzeyi & Testi",
    vibrationOnlyLabel = "Yalnızca Titreşim (Sessiz)",
    sectionQuran = "KUR'AN-I KERİM & TİLAVET",
    riwayahLabel = "Kıraat Rivayeti",
    scriptStyleLabel = "Kur'an Hat / Yazı Stili",
    reciterLabel = "Sesli Kâri (Okuyucu)",
    translationLabel = "Meal & Tefsir",
    arabicTextSizeLabel = "Arapça Yazı Boyutu",
    sectionMasjidMode = "CAMİ MODU & HUŞÛ KORUMASI",
    globalSilentLabel = "Genel Sessiz Mod",
    autoMasjidModeLabel = "Namazda Otomatik Sessiz Mod",
    autoMasjidDurationLabel = "Namaz Sırasında Sessizlik Süresi",
    sectionSystemDiagnostics = "SİSTEM & SENSÖRLER",
    compassDiagnosticsLabel = "Pusula Sensörleri & Tanılama",
    networkSyncLabel = "Ağ Eşitlemesi & Kaynak",
    resetDefaultsLabel = "Fabrika Ayarlarına Sıfırla",
    privacyPhilosophyTitle = "Gizlilik & Felsefe",

    cancel = "İptal",
    confirm = "Onayla",
    save = "Kaydet",
    done = "Tamam",
    close = "Kapat"
)

val UrduStrings = UiStrings(
    appName = "صلاۃ",
    navToday = "آج",
    navPrayer = "نماز",
    navQuran = "قرآن",
    navQibla = "قبلہ",
    navSettings = "ترتیبات",

    nextPrayerLabel = "اگلی نماز",
    adhanAt = "اذان کا وقت",
    viewDetails = "تفصیلات دیکھیں",
    currentPeriod = "موجودہ وقت",
    skyPeriodSuffix = "آسمان ✦",
    hoursUnit = "گھنٹے",
    minsUnit = "منٹ",
    secsUnit = "سیکنڈ",
    todaysPrayers = "آج کی نمازیں",
    tapToMarkCompleted = "مکمل کرنے پر نشان لگائیں",
    continueReading = "تلاوت جاری رکھیں",
    continueButton = "جاری رکھیں",
    sourceLabel = "ماخذ",
    alertsActive = "انتباہات فعال ہیں",
    silentModeOn = "خاموش موڈ آن ہے",
    masjidMode = "مسجد موڈ",
    resetToRealtime = "اصل وقت پر واپس آئیں",
    onlineStatus = "آن لائن",
    offlineStatus = "آف لائن",
    syncingStatus = "ہم آہنگی جاری",

    fajr = "فجر",
    sunrise = "طلوع آفتاب",
    dhuhr = "ظہر",
    asr = "عصر",
    maghrib = "مغرب",
    isha = "عشاء",

    transparentCalculationSource = "شفاف حساب کا شرعی ماخذ",
    todaysTimes = "آج کے اوقات",
    prayerTimesHeader = "اوقاتِ نماز",
    vigilsAndNightPeriods = "تہجد اور رات کے اوقات",
    imsakTitle = "امساک (فجر سے ۱۰ منٹ قبل)",
    midnightTitle = "شرعی نصف شب",
    lastThirdTitle = "رات کا آخری تہائی حصہ (تہجد)",
    monthlyCalendarHeader = "ماہانہ تقویم",
    todayBtn = "آج",

    qiblaDirectionTitle = "سمتِ قبلہ",
    sensoryCompassSubtitle = "کعبہ شریف کی طرف رخ دکھانے والا قطب نما",
    magneticInterferenceDetected = "مقناطیسی خلل پایا گیا",
    moveAwayMetal = "دھاتی چیزوں سے دور ہوں یا کیلیبریٹ کریں۔",
    kaabaDistance = "کعبہ شریف کا فاصلہ",
    trueNorth = "حقیقی شمال",
    magneticNorth = "مقناطیسی شمال",
    calibratedStatus = "اعلیٰ درستگی",
    facingQibla = "آپ کا رخ قبلہ کی طرف ہے",
    turnTowardsKaaba = "کعبہ کی طرف رخ کریں",

    surahTab = "سورت",
    pageTab = "صفحہ",
    juzTab = "پارہ",
    hizbTab = "حزب",
    bookmarksTab = "نشانات",
    searchSurahPlaceholder = "سورت کا نام یا نمبر تلاش کریں...",
    continueReadingBar = "تلاوت جاری رکھیں",
    versesCount = "آیات",
    meccan = "مکی",
    medinan = "مدنی",

    settingsTitle = "ترتیبات اور ترجیحات",
    sectionGeneral = "عام اور زبان",
    languageLabel = "زبان",
    appThemeLabel = "ایپ تھیم",
    timeFormatLabel = "۲۴ گھنٹے وقت کی ترتیب",
    sectionPrayerCalc = "اوقاتِ نماز اور حساب",
    locationLabel = "مقام",
    methodLabel = "طریقہ حساب",
    madhhabLabel = "فقہی مسلک (عصر)",
    adjustmentsLabel = "دستی منٹ ایڈجسٹمنٹ",
    hijriCalibrationLabel = "ہجری تاریخ کی ترتیب",
    sectionAudioAlerts = "اذان آڈیو اور نوٹیفکیشن",
    adhanCallLabel = "وقت پر اذان کی پکار",
    perPrayerModesLabel = "ہر نماز کے لیے الرٹ موڈ",
    prePrayerReminderLabel = "نماز سے قبل یاد دہانی",
    adhanSoundLabel = "مؤذن کی آواز",
    adhanVolumeLabel = "اذان کی آواز اور ٹیسٹ",
    vibrationOnlyLabel = "صرف وائبریشن (خاموش)",
    sectionQuran = "قرآن مجید اور تلاوت",
    riwayahLabel = "قرآنی روایت",
    scriptStyleLabel = "قرآنی رسم الخط",
    reciterLabel = "آڈیو قاری",
    translationLabel = "ترجمہ و تفسیر",
    arabicTextSizeLabel = "عربی فونٹ سائز",
    sectionMasjidMode = "مسجد موڈ اور خشوع",
    globalSilentLabel = "عام سائلنٹ موڈ",
    autoMasjidModeLabel = "نماز کے دوران خودکار سائلنٹ",
    autoMasjidDurationLabel = "نماز میں سائلنٹ کا دورانیہ",
    sectionSystemDiagnostics = "سسٹم اور سینسرز",
    compassDiagnosticsLabel = "قطب نما اور سینسر کی جانچ",
    networkSyncLabel = "نیٹ ورک سنک اور ماخذ",
    resetDefaultsLabel = "فیکٹری سیٹنگز پر بحال کریں",
    privacyPhilosophyTitle = "رازداری اور اصول",

    cancel = "منسوخ",
    confirm = "تصدیق",
    save = "محفوظ کریں",
    done = "مکمل",
    close = "بند کریں"
)

val MalayStrings = UiStrings(
    appName = "SALAH",
    navToday = "Hari Ini",
    navPrayer = "Solat",
    navQuran = "Al-Quran",
    navQibla = "Kiblat",
    navSettings = "Tetapan",

    nextPrayerLabel = "SOLAT SETERUSNYA",
    adhanAt = "Azan pada",
    viewDetails = "Lihat butiran",
    currentPeriod = "Waktu sekarang",
    skyPeriodSuffix = "Langit ✦",
    hoursUnit = "JAM",
    minsUnit = "MINIT",
    secsUnit = "SAAT",
    todaysPrayers = "Waktu Solat Hari Ini",
    tapToMarkCompleted = "Ketik untuk tanda selesai",
    continueReading = "TERUSKAN MEMBACA",
    continueButton = "Teruskan",
    sourceLabel = "Sumber",
    alertsActive = "Pemberitahuan Aktif",
    silentModeOn = "Mod Senyap AKTIF",
    masjidMode = "Mod Masjid",
    resetToRealtime = "Kembali ke Waktu Nyata",
    onlineStatus = "DALAM TALIAN",
    offlineStatus = "LUAR TALIAN",
    syncingStatus = "MENYELARAS",

    fajr = "Subuh",
    sunrise = "Syuruk",
    dhuhr = "Zohor",
    asr = "Asar",
    maghrib = "Maghrib",
    isha = "Isyak",

    transparentCalculationSource = "Sumber Pengiraan Telus",
    todaysTimes = "WAKTU HARI INI",
    prayerTimesHeader = "WAKTU SOLAT",
    vigilsAndNightPeriods = "WAKTU MALAM & TAHAJJUD",
    imsakTitle = "Imsak (10 minit sebelum Subuh)",
    midnightTitle = "Tengah Malam Islam",
    lastThirdTitle = "Sepertiga Malam Terakhir (Tahajjud)",
    monthlyCalendarHeader = "TAKWIM BULANAN",
    todayBtn = "Hari Ini",

    qiblaDirectionTitle = "Arah Kiblat",
    sensoryCompassSubtitle = "Kompas sensor tepat menghadap Kaabah",
    magneticInterferenceDetected = "Gangguan Magnet Dikesan",
    moveAwayMetal = "Jauhi objek logam atau ketik kalibrasi.",
    kaabaDistance = "Jarak ke Kaabah",
    trueNorth = "Utara Benar",
    magneticNorth = "Utara Magnetik",
    calibratedStatus = "KETEPATAN TINGGI",
    facingQibla = "Menghadap Kaabah",
    turnTowardsKaaba = "Pusing ke Arah Kaabah",

    surahTab = "Surah",
    pageTab = "Halaman",
    juzTab = "Juzuk",
    hizbTab = "Hizib",
    bookmarksTab = "Penanda",
    searchSurahPlaceholder = "Cari Surah mengikut nama atau nombor...",
    continueReadingBar = "Teruskan Bacaan",
    versesCount = "ayat",
    meccan = "Makkiyyah",
    medinan = "Madaniyyah",

    settingsTitle = "Tetapan & Konfigurasi",
    sectionGeneral = "UMUM & PENSETAN BAHASA",
    languageLabel = "Bahasa",
    appThemeLabel = "Tema Aplikasi",
    timeFormatLabel = "Format Masa 24 Jam",
    sectionPrayerCalc = "WAKTU SOLAT & PENGIRAAN",
    locationLabel = "Lokasi",
    methodLabel = "Kaedah Pengiraan",
    madhhabLabel = "Mazhab Fiqh (Asar)",
    adjustmentsLabel = "Pelarasan Minit Manual",
    hijriCalibrationLabel = "Kalibrasi Tarikh Hijrah",
    sectionAudioAlerts = "AUDIO AZAN & PEMBERITAHUAN",
    adhanCallLabel = "Panggilan Azan Tepat Waktu",
    perPrayerModesLabel = "Mod Makluman Setiap Solat",
    prePrayerReminderLabel = "Peringatan Sebelum Solat",
    adhanSoundLabel = "Suara Muazin Azan",
    adhanVolumeLabel = "Kelantangan & Ujian Audio Azan",
    vibrationOnlyLabel = "Getaran Sahaja (Senyap)",
    sectionQuran = "AL-QURAN & TILAWAH",
    riwayahLabel = "Riwayat Bacaan",
    scriptStyleLabel = "Gaya Khat Rasm Al-Quran",
    reciterLabel = "Qari Audio",
    translationLabel = "Terjemahan & Tafsir",
    arabicTextSizeLabel = "Saiz Teks Arab",
    sectionMasjidMode = "MOD MASJID & KEKHUSYUKAN",
    globalSilentLabel = "Mod Senyap Menyeluruh",
    autoMasjidModeLabel = "Mod Senyap Automatik Semasa Solat",
    autoMasjidDurationLabel = "Tempoh Senyap Semasa Solat",
    sectionSystemDiagnostics = "SISTEM & DIAGNOSTIK",
    compassDiagnosticsLabel = "Sensor Kompas & Diagnostik",
    networkSyncLabel = "Penyelarasan Rangkaian & Sumber",
    resetDefaultsLabel = "Tetapkan Semula ke Asal",
    privacyPhilosophyTitle = "Privasi & Falsafah",

    cancel = "Batal",
    confirm = "Sahkan",
    save = "Simpan",
    done = "Selesai",
    close = "Tutup"
)

val BengaliStrings = UiStrings(
    appName = "সালাহ",
    navToday = "আজ",
    navPrayer = "নামাজ",
    navQuran = "কুরআন",
    navQibla = "কিবলা",
    navSettings = "সেটিংস",

    nextPrayerLabel = "পরবর্তী নামাজ",
    adhanAt = "আজান হবে",
    viewDetails = "বিস্তারিত দেখুন",
    currentPeriod = "বর্তমান ওয়াক্ত",
    skyPeriodSuffix = "আকাশ ✦",
    hoursUnit = "ঘণ্টা",
    minsUnit = "মিনিট",
    secsUnit = "সেকেন্ড",
    todaysPrayers = "আজকের নামাজের সময়সূচি",
    tapToMarkCompleted = "আদায় চিহ্নিত করতে ট্যাপ করুন",
    continueReading = "তেলাওয়াত চালিয়ে যান",
    continueButton = "চালিয়ে যান",
    sourceLabel = "উৎস",
    alertsActive = "সতর্কবার্তা সক্রিয়",
    silentModeOn = "সাইলেন্ট মোড চালু",
    masjidMode = "মসজিদ মোড",
    resetToRealtime = "রিয়েল-টাইমে ফিরুন",
    onlineStatus = "অনলাইন",
    offlineStatus = "অফলাইন",
    syncingStatus = "সিঙ্ক হচ্ছে",

    fajr = "ফজর",
    sunrise = "সূর্যোদয়",
    dhuhr = "জোহর",
    asr = "আসর",
    maghrib = "মাগরিব",
    isha = "ইশা",

    transparentCalculationSource = "স্বচ্ছ হিসাব পদ্ধতি ও উৎস",
    todaysTimes = "আজকের সময়সূচি",
    prayerTimesHeader = "নামাজের ওয়াক্ত",
    vigilsAndNightPeriods = "তাহাজ্জুদ ও রাতের ওয়াক্ত",
    imsakTitle = "ইমসাক (ফজরের ১০ মিনিট আগে)",
    midnightTitle = "শরয়ী মধ্যরাত",
    lastThirdTitle = "রাতের শেষ তৃতীয়াংশ (তাহাজ্জুদ)",
    monthlyCalendarHeader = "মাসিক ক্যালেন্ডার",
    todayBtn = "আজ",

    qiblaDirectionTitle = "কিবলার দিক",
    sensoryCompassSubtitle = "কাবা শরীফের সঠিক দিকনির্দেশক কম্পাস",
    magneticInterferenceDetected = "চৌম্বকীয় বিভ্রান্তি শনাক্ত হয়েছে",
    moveAwayMetal = "ধাতব বস্তু থেকে দূরে সরে যান বা ক্যালিব্রেট করুন।",
    kaabaDistance = "কাবা শরীফের দূরত্ব",
    trueNorth = "প্রকৃত উত্তর",
    magneticNorth = "চৌম্বকীয় উত্তর",
    calibratedStatus = "উচ্চ নির্ভুলতা",
    facingQibla = "কাবার সম্মুখবর্তী",
    turnTowardsKaaba = "কাবার দিকে মুখ করুন",

    surahTab = "সূরা",
    pageTab = "পৃষ্ঠা",
    juzTab = "পারা",
    hizbTab = "হিযব",
    bookmarksTab = "বুকমার্ক",
    searchSurahPlaceholder = "সূরা নাম বা নম্বর দিয়ে খুঁজুন...",
    continueReadingBar = "পড়া চালিয়ে যান",
    versesCount = "আয়াত",
    meccan = "মাক্কী",
    medinan = "মাদানী",

    settingsTitle = "সেটিংস ও কনফিগারেশন",
    sectionGeneral = "সাধারণ ও ভাষা",
    languageLabel = "ভাষা",
    appThemeLabel = "অ্যাপ থিম",
    timeFormatLabel = "২৪ ঘণ্টার সময় ফরম্যাট",
    sectionPrayerCalc = "নামাজের সময় ও হিসাব",
    locationLabel = "অবস্থান",
    methodLabel = "হিসাব পদ্ধতি",
    madhhabLabel = "আসর ফিকহ মাজহাব",
    adjustmentsLabel = "ম্যানুয়াল মিনিট সমন্বয়",
    hijriCalibrationLabel = "হিজরি তারিখ সমন্বয়",
    sectionAudioAlerts = "আজান ও বিজ্ঞপ্তি",
    adhanCallLabel = "ওয়াক্তে আজানের আহ্বান",
    perPrayerModesLabel = "প্রতি ওয়াক্তের সতর্কবার্তা মোড",
    prePrayerReminderLabel = "নামাজের আগের রিমাইন্ডার",
    adhanSoundLabel = "মুয়াজ্জিনের কণ্ঠ",
    adhanVolumeLabel = "আজানের সাউন্ড ও অডিও টেস্ট",
    vibrationOnlyLabel = "শুধুমাত্র কম্পন (নীরব)",
    sectionQuran = "পবিত্র কুরআন ও তেলাওয়াত",
    riwayahLabel = "ক্বেরাত রেওয়ায়েত",
    scriptStyleLabel = "কুরআনের ক্যালিগ্রাফি স্টাইল",
    reciterLabel = "ক্বারী কণ্ঠ",
    translationLabel = "অনুবাদ ও তাফসীর",
    arabicTextSizeLabel = "আরবি হরফের আকার",
    sectionMasjidMode = "মসজিদ মোড ও একাগ্রতা",
    globalSilentLabel = "সাধারণ সাইলেন্ট মোড",
    autoMasjidModeLabel = "নামাজে স্বয়ংক্রিয় নীরব মোড",
    autoMasjidDurationLabel = "নামাজে নীরবতার স্থায়িত্ব",
    sectionSystemDiagnostics = "সিস্টেম ও সেন্সর",
    compassDiagnosticsLabel = "কম্পাস সেন্সর ও ডায়াগনস্টিক",
    networkSyncLabel = "নেটওয়ার্ক সিঙ্ক ও উৎস",
    resetDefaultsLabel = "ফ্যাক্টরি সেটিংসে রিসেট করুন",
    privacyPhilosophyTitle = "গোপনীয়তা ও নীতি",

    cancel = "বাতিল",
    confirm = "নিশ্চিত",
    save = "সংরক্ষণ",
    done = "সম্পন্ন",
    close = "বন্ধ করুন"
)

val RussianStrings = UiStrings(
    appName = "SALAH",
    navToday = "Сегодня",
    navPrayer = "Намаз",
    navQuran = "Коран",
    navQibla = "Кибла",
    navSettings = "Настройки",

    nextPrayerLabel = "СЛЕДУЮЩИЙ НАМАЗ",
    adhanAt = "Азан в",
    viewDetails = "Подробнее",
    currentPeriod = "Текущее время",
    skyPeriodSuffix = "Небо ✦",
    hoursUnit = "ЧАС",
    minsUnit = "МИН",
    secsUnit = "СЕК",
    todaysPrayers = "Расписание на сегодня",
    tapToMarkCompleted = "Нажмите, чтобы отметить выполненным",
    continueReading = "ПРОДОЛЖИТЬ ЧТЕНИЕ",
    continueButton = "Продолжить",
    sourceLabel = "Источник",
    alertsActive = "Оповещения активны",
    silentModeOn = "Беззвучный режим ВКЛ",
    masjidMode = "Режим мечети",
    resetToRealtime = "Вернуться к текущему времени",
    onlineStatus = "ОНЛАЙН",
    offlineStatus = "ОФФЛАЙН",
    syncingStatus = "СИНХРОНИЗАЦИЯ",

    fajr = "Фаджр",
    sunrise = "Восход",
    dhuhr = "Зухр",
    asr = "Аср",
    maghrib = "Магриб",
    isha = "Иша",

    transparentCalculationSource = "Прозрачный метод расчета",
    todaysTimes = "ВРЕМЯ НА СЕГОДНЯ",
    prayerTimesHeader = "ВРЕМЯ НАМАЗА",
    vigilsAndNightPeriods = "НОЧНЫЕ ПЕРИОДЫ И ТАХАДЖУД",
    imsakTitle = "Имсак (за 10 мин до Фаджра)",
    midnightTitle = "Исламская полночь",
    lastThirdTitle = "Последняя треть ночи (Тахаджуд)",
    monthlyCalendarHeader = "МЕСЯЧНЫЙ КАЛЕНДАРЬ",
    todayBtn = "Сегодня",

    qiblaDirectionTitle = "Направление Киблы",
    sensoryCompassSubtitle = "Точный компас с указанием на Каабу",
    magneticInterferenceDetected = "Обнаружены магнитные помехи",
    moveAwayMetal = "Отойдите от металлических предметов.",
    kaabaDistance = "Расстояние до Каабы",
    trueNorth = "Истинный север",
    magneticNorth = "Магнитный север",
    calibratedStatus = "ВЫСОКАЯ ТОЧНОСТЬ",
    facingQibla = "Вы смотрите на Каабу",
    turnTowardsKaaba = "Повернитесь в сторону Каабы",

    surahTab = "Сура",
    pageTab = "Стр",
    juzTab = "Джуз",
    hizbTab = "Хизб",
    bookmarksTab = "Закладки",
    searchSurahPlaceholder = "Поиск суры по названию или номеру...",
    continueReadingBar = "Продолжить чтение",
    versesCount = "аятов",
    meccan = "Мекканская",
    medinan = "Мединская",

    settingsTitle = "Настройки и конфигурация",
    sectionGeneral = "ОБЩИЕ И ЯЗЫК",
    languageLabel = "Язык интерфейса",
    appThemeLabel = "Тема приложения",
    timeFormatLabel = "24-часовой формат",
    sectionPrayerCalc = "ВРЕМЯ НАМАЗА И РАСЧЕТ",
    locationLabel = "Местоположение",
    methodLabel = "Метод расчета",
    madhhabLabel = "Мазхаб (Аср)",
    adjustmentsLabel = "Ручная корректировка (минуты)",
    hijriCalibrationLabel = "Калибровка календаря Хиджры",
    sectionAudioAlerts = "АЗАН И УВЕДОМЛЕНИЯ",
    adhanCallLabel = "Звук азана при наступлении времени",
    perPrayerModesLabel = "Режимы оповещения для каждого намаза",
    prePrayerReminderLabel = "Напоминание перед намазом",
    adhanSoundLabel = "Голос муэдзина",
    adhanVolumeLabel = "Громкость и проверка азана",
    vibrationOnlyLabel = "Только вибрация (Без звука)",
    sectionQuran = "СВЯЩЕННЫЙ КОРАН И ЧТЕНИЕ",
    riwayahLabel = "Риваят (Традиция чтения)",
    scriptStyleLabel = "Стиль шрифта Корана",
    reciterLabel = "Чтец Корана",
    translationLabel = "Перевод и тафсир",
    arabicTextSizeLabel = "Размер арабского шрифта",
    sectionMasjidMode = "РЕЖИМ МЕЧЕТИ И СПОКОЙСТВИЕ",
    globalSilentLabel = "Общий беззвучный режим",
    autoMasjidModeLabel = "Авто-беззвучный режим во время намаза",
    autoMasjidDurationLabel = "Длительность беззвучного режима",
    sectionSystemDiagnostics = "СИСТЕМА И ДАТЧИКИ",
    compassDiagnosticsLabel = "Датчики компаса и диагностика",
    networkSyncLabel = "Синхронизация с сетью и источник",
    resetDefaultsLabel = "Сброс к заводским настройкам",
    privacyPhilosophyTitle = "Конфиденциальность и философия",

    cancel = "Отмена",
    confirm = "Подтвердить",
    save = "Сохранить",
    done = "Готово",
    close = "Закрыть"
)

val GermanStrings = UiStrings(
    appName = "SALAH",
    navToday = "Heute",
    navPrayer = "Gebet",
    navQuran = "Koran",
    navQibla = "Qibla",
    navSettings = "Einstellungen",

    nextPrayerLabel = "NÄCHSTES GEBET",
    adhanAt = "Adhan um",
    viewDetails = "Details ansehen",
    currentPeriod = "Aktuelle Zeit",
    skyPeriodSuffix = "Himmel ✦",
    hoursUnit = "STD",
    minsUnit = "MIN",
    secsUnit = "SEK",
    todaysPrayers = "Heutige Gebetszeiten",
    tapToMarkCompleted = "Tippen zum Abhaken",
    continueReading = "LESEN FORTSETZEN",
    continueButton = "Fortsetzen",
    sourceLabel = "Quelle",
    alertsActive = "Erinnerungen aktiv",
    silentModeOn = "Stummmodus AN",
    masjidMode = "Moschee-Modus",
    resetToRealtime = "Zurück zur Echtzeit",
    onlineStatus = "ONLINE",
    offlineStatus = "OFFLINE",
    syncingStatus = "SYNCHRONISIERUNG",

    fajr = "Fajr",
    sunrise = "Sonnenaufgang",
    dhuhr = "Dhuhr",
    asr = "Asr",
    maghrib = "Maghrib",
    isha = "Isha",

    transparentCalculationSource = "Transparente Berechnungsmethode",
    todaysTimes = "HEUTIGE ZEITEN",
    prayerTimesHeader = "GEBETSZEITEN",
    vigilsAndNightPeriods = "NACHTWACHEN & TAHAJJUD",
    imsakTitle = "Imsak (10 Min vor Fajr)",
    midnightTitle = "Islamische Mitternacht",
    lastThirdTitle = "Letztes Drittel der Nacht (Tahajjud)",
    monthlyCalendarHeader = "MONATSKALENDER",
    todayBtn = "Heute",

    qiblaDirectionTitle = "Qibla-Richtung",
    sensoryCompassSubtitle = "Präziser Kompass zur Kaaba",
    magneticInterferenceDetected = "Magnetische Störung erkannt",
    moveAwayMetal = "Von Metallgegenständen entfernen oder kalibrieren.",
    kaabaDistance = "Entfernung zur Kaaba",
    trueNorth = "Geographisch Nord",
    magneticNorth = "Magnetisch Nord",
    calibratedStatus = "HOHE GENAUIGKEIT",
    facingQibla = "Ausgerichtet zur Kaaba",
    turnTowardsKaaba = "Drehen Sie sich zur Kaaba",

    surahTab = "Sure",
    pageTab = "Seite",
    juzTab = "Juz'",
    hizbTab = "Hizb",
    bookmarksTab = "Lesezeichen",
    searchSurahPlaceholder = "Sure nach Name oder Nummer suchen...",
    continueReadingBar = "Weiterlesen",
    versesCount = "Verse",
    meccan = "Mekkanisch",
    medinan = "Medinensisch",

    settingsTitle = "Einstellungen & Konfiguration",
    sectionGeneral = "ALLGEMEIN & SPRACHE",
    languageLabel = "Sprache",
    appThemeLabel = "App-Design",
    timeFormatLabel = "24-Stunden-Zeitformat",
    sectionPrayerCalc = "GEBETSZEITEN & BERECHNUNG",
    locationLabel = "Standort",
    methodLabel = "Berechnungsmethode",
    madhhabLabel = "Rechtsschule (Asr)",
    adjustmentsLabel = "Manuelle Minutenanpassung",
    hijriCalibrationLabel = "Hidschri-Kalibrierung",
    sectionAudioAlerts = "ADHAN & BENACHRICHTIGUNGEN",
    adhanCallLabel = "Gebetsruf zur Gebetszeit",
    perPrayerModesLabel = "Benachrichtigungsmodi pro Gebet",
    prePrayerReminderLabel = "Erinnerung vor dem Gebet",
    adhanSoundLabel = "Muezzin-Stimme",
    adhanVolumeLabel = "Lautstärke & Audiotest",
    vibrationOnlyLabel = "Nur Vibration (Lautlos)",
    sectionQuran = "DER HEILIGE KORAN & REZITATION",
    riwayahLabel = "Riwayah (Überlieferungstradition)",
    scriptStyleLabel = "Schriftstil des Korans",
    reciterLabel = "Rezitator",
    translationLabel = "Übersetzung & Exegese",
    arabicTextSizeLabel = "Arabische Schriftgröße",
    sectionMasjidMode = "MOSCHEE-MODUS & RUHE",
    globalSilentLabel = "Globaler Stummmodus",
    autoMasjidModeLabel = "Automatischer Stummmodus beim Gebet",
    autoMasjidDurationLabel = "Dauer der Stummschaltung",
    sectionSystemDiagnostics = "SYSTEM & SENSOREN",
    compassDiagnosticsLabel = "Kompasssensoren & Diagnose",
    networkSyncLabel = "Netzwerksynchronisation & Quelle",
    resetDefaultsLabel = "Auf Werkseinstellungen zurücksetzen",
    privacyPhilosophyTitle = "Datenschutz & Philosophie",

    cancel = "Abbrechen",
    confirm = "Bestätigen",
    save = "Speichern",
    done = "Fertig",
    close = "Schließen"
)

val SpanishStrings = UiStrings(
    appName = "SALAH",
    navToday = "Hoy",
    navPrayer = "Oración",
    navQuran = "Corán",
    navQibla = "Alquibla",
    navSettings = "Ajustes",

    nextPrayerLabel = "PRÓXIMA ORACIÓN",
    adhanAt = "Adhan a las",
    viewDetails = "Ver detalles",
    currentPeriod = "Período actual",
    skyPeriodSuffix = "Cielo ✦",
    hoursUnit = "HORAS",
    minsUnit = "MIN",
    secsUnit = "SEG",
    todaysPrayers = "Horarios de hoy",
    tapToMarkCompleted = "Toca para marcar cumplida",
    continueReading = "CONTINUAR LEYENDO",
    continueButton = "Continuar",
    sourceLabel = "Fuente",
    alertsActive = "Alertas activas",
    silentModeOn = "Modo silencioso ACTIVADO",
    masjidMode = "Modo Mezquita",
    resetToRealtime = "Restablecer a tiempo real",
    onlineStatus = "EN LÍNEA",
    offlineStatus = "SIN CONEXIÓN",
    syncingStatus = "SINCRONIZANDO",

    fajr = "Fajr",
    sunrise = "Amanecer",
    dhuhr = "Dhuhr",
    asr = "Asr",
    maghrib = "Maghrib",
    isha = "Isha",

    transparentCalculationSource = "Fuente de cálculo transparente",
    todaysTimes = "HORARIOS DE HOY",
    prayerTimesHeader = "HORARIOS DE ORACIÓN",
    vigilsAndNightPeriods = "VIGILIAS Y NOCHE",
    imsakTitle = "Imsak (10 min antes de Fajr)",
    midnightTitle = "Medianoche islámica",
    lastThirdTitle = "Último tercio de la noche (Taháyyud)",
    monthlyCalendarHeader = "CALENDARIO MENSUAL",
    todayBtn = "Hoy",

    qiblaDirectionTitle = "Dirección de la Alquibla",
    sensoryCompassSubtitle = "Brújula sensorial orientada hacia la Kaaba",
    magneticInterferenceDetected = "Interferencia magnética detectada",
    moveAwayMetal = "Aléjese de objetos metálicos o calibre.",
    kaabaDistance = "Distancia a la Kaaba",
    trueNorth = "Norte verdadero",
    magneticNorth = "Norte magnético",
    calibratedStatus = "ALTA PRECISIÓN",
    facingQibla = "Frente a la Kaaba",
    turnTowardsKaaba = "Gire hacia la Kaaba",

    surahTab = "Sura",
    pageTab = "Pág",
    juzTab = "Yuz'",
    hizbTab = "Hizb",
    bookmarksTab = "Marcadores",
    searchSurahPlaceholder = "Buscar sura por nombre o número...",
    continueReadingBar = "Continuar lectura",
    versesCount = "aleyas",
    meccan = "Mequí",
    medinan = "Mediní",

    settingsTitle = "Ajustes y Configuración",
    sectionGeneral = "GENERAL Y LOCALIZACIÓN",
    languageLabel = "Idioma",
    appThemeLabel = "Tema de la aplicación",
    timeFormatLabel = "Formato de hora 24h",
    sectionPrayerCalc = "HORARIOS Y CÁLCULO",
    locationLabel = "Ubicación",
    methodLabel = "Método de cálculo",
    madhhabLabel = "Escuela jurídica (Asr)",
    adjustmentsLabel = "Ajustes manuales (minutos)",
    hijriCalibrationLabel = "Calibración fecha hiyri",
    sectionAudioAlerts = "AUDIO ADHAN Y NOTIFICACIONES",
    adhanCallLabel = "Llamada a la oración puntual",
    perPrayerModesLabel = "Modos de alerta por oración",
    prePrayerReminderLabel = "Recordatorio antes de la oración",
    adhanSoundLabel = "Voz del muecín",
    adhanVolumeLabel = "Volumen y prueba de audio",
    vibrationOnlyLabel = "Solo vibración (Silencioso)",
    sectionQuran = "EL NOBLE CORÁN Y RECITACIÓN",
    riwayahLabel = "Riwāyah (Tradición de recitación)",
    scriptStyleLabel = "Estilo de caligrafía coránica",
    reciterLabel = "Recitador de audio",
    translationLabel = "Traducción y exégesis",
    arabicTextSizeLabel = "Tamaño del texto árabe",
    sectionMasjidMode = "MODO MEZQUITA Y SOSIEGO",
    globalSilentLabel = "Modo silencioso global",
    autoMasjidModeLabel = "Modo silencioso automático en oración",
    autoMasjidDurationLabel = "Duración del silencio en oración",
    sectionSystemDiagnostics = "SISTEMA Y SENSORES",
    compassDiagnosticsLabel = "Sensores de brújula y diagnóstico",
    networkSyncLabel = "Sincronización de red y fuente",
    resetDefaultsLabel = "Restablecer a valores de fábrica",
    privacyPhilosophyTitle = "Privacidad y Filosofía",

    cancel = "Cancelar",
    confirm = "Confirmar",
    save = "Guardar",
    done = "Listo",
    close = "Cerrar"
)

object LocalizationManager {
    fun getStrings(languageNameOrCode: String): UiStrings {
        return when (AppLanguage.fromNameOrCode(languageNameOrCode)) {
            AppLanguage.ENGLISH -> EnglishStrings
            AppLanguage.ARABIC -> ArabicStrings
            AppLanguage.FRENCH -> FrenchStrings
            AppLanguage.INDONESIAN -> IndonesianStrings
            AppLanguage.TURKISH -> TurkishStrings
            AppLanguage.URDU -> UrduStrings
            AppLanguage.MALAY -> MalayStrings
            AppLanguage.BENGALI -> BengaliStrings
            AppLanguage.RUSSIAN -> RussianStrings
            AppLanguage.GERMAN -> GermanStrings
            AppLanguage.SPANISH -> SpanishStrings
        }
    }
}

val LocalStrings = staticCompositionLocalOf { EnglishStrings }

val UiStrings.navPrayers: String
    get() = navPrayer

val UiStrings.gotIt: String
    get() = done

val UiStrings.ayahLabel: String
    get() = when (this) {
        ArabicStrings -> "آية"
        UrduStrings -> "آیت"
        TurkishStrings -> "Ayet"
        IndonesianStrings -> "Ayat"
        MalayStrings -> "Ayat"
        BengaliStrings -> "আয়াত"
        RussianStrings -> "Аят"
        GermanStrings -> "Vers"
        SpanishStrings -> "Aleya"
        FrenchStrings -> "Verset"
        else -> "Ayah"
    }

/**
 * Quran reader strings (nour-style reading experience).
 * English defaults; other languages fall back to English until translated.
 */
val UiStrings.cardsModeLabel: String get() = "Cards"
val UiStrings.continuousModeLabel: String get() = "Continuous"
val UiStrings.readingSettingsLabel: String get() = "Reading settings"
val UiStrings.backToSurahsLabel: String get() = "Back to surahs"
val UiStrings.copyVerseLabel: String get() = "Copy verse"
val UiStrings.shareVerseLabel: String get() = "Share verse"
val UiStrings.verseCopiedToast: String get() = "Verse copied"
val UiStrings.shareChooserTitle: String get() = "Share verse via"
val UiStrings.translationSectionTitle: String get() = "Translation"
val UiStrings.showTranslationLabel: String get() = "Show"
val UiStrings.hideTranslationLabel: String get() = "Hide"
val UiStrings.translationCreditLine: String get() = "English — Saheeh International"
val UiStrings.tapVerseHint: String get() = "Tap a verse to inspect it"
val UiStrings.popularSurahsLabel: String get() = "Popular surahs"
val UiStrings.searchVersesHint: String get() = "Search Arabic text or English translation..."
val UiStrings.translationNotAvailable: String get() = "Translation not available"

fun UiStrings.prayerName(prayer: com.example.data.model.Prayer): String {
    return when (prayer) {
        com.example.data.model.Prayer.FAJR -> fajr
        com.example.data.model.Prayer.SUNRISE -> sunrise
        com.example.data.model.Prayer.DHUHR -> dhuhr
        com.example.data.model.Prayer.ASR -> asr
        com.example.data.model.Prayer.MAGHRIB -> maghrib
        com.example.data.model.Prayer.ISHA -> isha
    }
}

/**
 * Applies the selected language.
 *
 * Also sets [LocalLayoutDirection]. The project previously tracked
 * `AppLanguage.isRtl` (true for Arabic and Urdu) but never used it, so Arabic
 * and Urdu interfaces rendered left-to-right with the labels merely swapped.
 * Providing the direction here means `start`/`end` padding, row order and the
 * auto-mirrored icons all follow the language, in one place.
 */
@Composable
fun ProvideAppLanguage(language: String, content: @Composable () -> Unit) {
    val strings = LocalizationManager.getStrings(language)
    val direction = if (AppLanguage.fromNameOrCode(language).isRtl) {
        LayoutDirection.Rtl
    } else {
        LayoutDirection.Ltr
    }
    CompositionLocalProvider(
        LocalStrings provides strings,
        LocalLayoutDirection provides direction
    ) {
        content()
    }
}
